import 'package:flutter/material.dart';

Color whiteColor = Colors.white;
Color blackColor = Colors.black;
Color transparentColor = Colors.transparent;
Color syanColor = const Color(0xff31BBAC);
Color holdorangeColor = const Color(0xffFF1E00);
Color lightblueColor = const Color(0xff3186AC);
Color lightorangeColor = const Color(0xffFF9933);
Color greyColor = const Color(0xff999999);
Color lightblackColor = const Color(0xff333333);
Color activecolor = const Color(0xff707070);
Color borderGreyColor = const Color(0xffCCCCCC);
Color changenumberorange = const Color(0xffFF6833);
Color warningcolor = const Color(0xfff7941e);
Color toastgrey = const Color(0xff414042);
Color errorcolor = const Color(0xffff0000);
Color lightGreyColor = const Color(0xffEFEFEF);
Color container_grey_color = const Color(0xffF1F1F1);
Color divider_grey_color = const Color(0xffE2E2E2);
Color signout_button = const Color(0xFF4D9EB7);
